sudo: required

services:
  - docker

before_install:
  - sudo chmod -R 777 server

script:
  - cd server
  - docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:nightly-2019-09-05 cargo build --release
  - docker build -t wafflespeanut/static-server .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push wafflespeanut/static-server
