sudo: required

services:
  - docker

script:
  - cd server
  - docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder cargo build --release
  - docker build -t wafflespeanut/static-server .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push wafflespeanut/static-server
