[package]
name = "server"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]

[dependencies]
chrono = "0.4"
env_logger = "0.4"
iron = "0.5"
lazy_static = "0.2"
log = "0.3"
mount = "0.3"
staticfile = "0.4"
