name: build-and-push

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    container:
      image: ekidd/rust-musl-builder:stable
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: cd server && cargo build --release
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: wafflespeanut/static-server:latest
